/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IUserInput } from "./components/stencil-input/stencil-input";
export namespace Components {
    interface StencilInput {
        "inputId"?: string;
        "label"?: string;
        "placeholder"?: string;
        "size"?: "small" | "medium" | "large" | "full";
        "type"?: string;
        "validationPattern"?: string;
    }
}
export interface StencilInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStencilInputElement;
}
declare global {
    interface HTMLStencilInputElement extends Components.StencilInput, HTMLStencilElement {
    }
    var HTMLStencilInputElement: {
        prototype: HTMLStencilInputElement;
        new (): HTMLStencilInputElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-input": HTMLStencilInputElement;
    }
}
declare namespace LocalJSX {
    interface StencilInput {
        "inputId"?: string;
        "label"?: string;
        "onUserInput"?: (event: StencilInputCustomEvent<IUserInput>) => void;
        "placeholder"?: string;
        "size"?: "small" | "medium" | "large" | "full";
        "type"?: string;
        "validationPattern"?: string;
    }
    interface IntrinsicElements {
        "stencil-input": StencilInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-input": LocalJSX.StencilInput & JSXBase.HTMLAttributes<HTMLStencilInputElement>;
        }
    }
}
